<?php

return [
    'cache_enabled' => env('NAVIGATION_CACHE_ENABLED', false),
    'cache_ttl' => 3600, // Cache duration in seconds (1 hour)
    'default_permissions' => ['view'],
    'items' => [
        'Dashboard' => [
            'title' => 'Dashboard',
            'icon' => 'bi bi-speedometer me-1',
            'route' => null,
            'parent_id' => null,
            'order' => 0,
            'parameters' => [],
            'permission' => null,
            'types' => null,
            'is_active' => true,
        ],
        'User' => [
            'title' => 'User',
            'icon' => 'bi bi-person-circle me-1',
            'route' => null,
            'parent_id' => null,
            'order' => 0,
            'parameters' => [],
            'permission' => null,
            'types' => null,
            'is_active' => true,
            'children' => [
                'User List' => [
                    'title' => 'User List',
                    'icon' => 'bi bi-people me-1',
                    'route' => 'users.index',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'User Create' => [
                    'title' => 'User Create',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'users.create',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'User Edit' => [
                    'title' => 'User Edit',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'users.edit',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['user' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
                'User Show' => [
                    'title' => 'User Show',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'users.show',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['user' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
            ]
        ],
        'Company' => [
            'title' => 'Company',
            'icon' => 'bi bi-person-circle me-1',
            'route' => null,
            'parent_id' => null,
            'order' => 0,
            'parameters' => [],
            'permission' => null,
            'types' => null,
            'is_active' => true,
            'children' => [
                'Company List' => [
                    'title' => 'Company List',
                    'icon' => 'bi bi-people me-1',
                    'route' => 'companies.index',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'Company Create' => [
                    'title' => 'Company Create',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'companies.create',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'Company Edit' => [
                    'title' => 'Company Edit',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'companies.edit',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['company' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
                'Company Show' => [
                    'title' => 'Company Show',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'companies.show',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['company' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
            ]
        ],
        'Product' => [
            'title' => 'Product',
            'icon' => 'bi bi-person-circle me-1',
            'route' => null,
            'parent_id' => null,
            'order' => 0,
            'parameters' => [],
            'permission' => null,
            'types' => null,
            'is_active' => true,
            'children' => [
                'Product List' => [
                    'title' => 'Product List',
                    'icon' => 'bi bi-people me-1',
                    'route' => 'products.index',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'Product Create' => [
                    'title' => 'Product Create',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'products.create',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => [],
                    'permission' => null,
                    'types' => null,
                    'is_active' => true,
                ],
                'Product Edit' => [
                    'title' => 'Product Edit',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'products.edit',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['product' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
                'Product Show' => [
                    'title' => 'Product Show',
                    'icon' => 'bi bi-person me-1',
                    'route' => 'products.show',
                    // 'parent_id' => null,
                    'order' => 0,
                    'parameters' => ['product' => 0],
                    'permission' => null,
                    'types' => null,
                    'is_active' => false,
                ],
            ]
        ],
    ],
];
